# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Preserve line number information for debugging stack traces.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# --- Room (database) ---
# Keep Room-generated DAO implementations and type converters.
-keep class * extends androidx.room.RoomDatabase { *; }
-keep @androidx.room.Entity class * { *; }
-keep @androidx.room.Dao class * { *; }
-keep @androidx.room.Database class * { *; }
-keepclassmembers class * {
    @androidx.room.* <methods>;
}

# --- Moshi ---
# Keep generated Moshi adapters generated by KSP/KAPT.
-keepclassmembers class * {
    @com.squareup.moshi.FromJson <methods>;
    @com.squareup.moshi.ToJson <methods>;
}
-keepclassmembers class * extends com.squareup.moshi.JsonAdapter { *; }
-dontwarn javax.annotation.**
-dontwarn org.jetbrains.annotations.**

# --- Retrofit & OkHttp ---
-keepattributes Signature, InnerClasses, EnclosingMethod, *Annotation*
-keep,allowshrinking,allowobfuscation interface retrofit2.Call
-keep,allowshrinking,allowobfuscation interface retrofit2.Response
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}
-dontwarn okhttp3.internal.platform.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**

# Keep kotlinx.coroutines internal debug markers.
-dontwarn kotlinx.coroutines.debug.**

# --- Media3 / ExoPlayer ---
# Keep Media3 session callbacks, commands and model classes referenced by reflection.
-keep class androidx.media3.session.* { *; }
-keepclassmembers class androidx.media3.session.* {
    public *;
}
-dontwarn androidx.media3.**

# --- Coil ---
-dontwarn coil.**

# --- Kotlin metadata ---
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations, AnnotationDefault

# --- Our own app code (kept for clarity; app classes are not obfuscated by default) ---
-keep class com.example.MainActivity { *; }
-keep class com.example.service.MusicPlaybackService { *; }